# Generated by Django 4.2.6 on 2023-10-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
